import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { redirect } from 'next/navigation'
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar";
import { createClient } from '@/lib/supabase/server'
import { getProfile } from '@/lib/database/queries'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const supabase = await createClient()

    const { data, error } = await supabase.auth.getClaims()
    if (error || !data?.claims) {
      redirect('/auth/login')
    }
  
    const userId = data.claims.sub
  
    try {
      // Check if user has a profile and if onboarding is completed
      const profile = await getProfile(userId)
      
      if (!profile || !profile.onboarding_completed) {
        redirect('/onboarding')
      }

    return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
        <AppSidebar />
        <SidebarTrigger />
        {children}
       
        </SidebarProvider>
      </body>
    </html>
  );
    } catch (error) {
        // If profile doesn't exist, redirect to onboarding
        console.error('Error fetching profile:', error)
        redirect('/onboarding')
    }
}
